# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 602)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(10, 10, 100, 31))
        self.StartButton.setObjectName("StartButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(120, 10, 100, 31))
        self.StopButton.setObjectName("StopButton")
        self.PortDropDownList = QtWidgets.QComboBox(self.centralwidget)
        self.PortDropDownList.setGeometry(QtCore.QRect(230, 10, 211, 31))
        self.PortDropDownList.setObjectName("PortDropDownList")
        self.SetPointBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SetPointBox.setGeometry(QtCore.QRect(10, 60, 189, 74))
        self.SetPointBox.setObjectName("SetPointBox")
        self.gridLayout = QtWidgets.QGridLayout(self.SetPointBox)
        self.gridLayout.setObjectName("gridLayout")
        self.SetPointSpinBox = QtWidgets.QDoubleSpinBox(self.SetPointBox)
        self.SetPointSpinBox.setObjectName("SetPointSpinBox")
        self.gridLayout.addWidget(self.SetPointSpinBox, 0, 0, 1, 1)
        self.SetPointSendButton = QtWidgets.QPushButton(self.SetPointBox)
        self.SetPointSendButton.setObjectName("SetPointSendButton")
        self.gridLayout.addWidget(self.SetPointSendButton, 0, 1, 1, 1)
        self.KpBox = QtWidgets.QGroupBox(self.centralwidget)
        self.KpBox.setGeometry(QtCore.QRect(10, 160, 189, 74))
        self.KpBox.setObjectName("KpBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.KpBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.KpSendButton = QtWidgets.QPushButton(self.KpBox)
        self.KpSendButton.setObjectName("KpSendButton")
        self.gridLayout_2.addWidget(self.KpSendButton, 0, 1, 1, 1)
        self.KpSpinBox = QtWidgets.QDoubleSpinBox(self.KpBox)
        self.KpSpinBox.setObjectName("KpSpinBox")
        self.gridLayout_2.addWidget(self.KpSpinBox, 0, 0, 1, 1)
        self.KiBox = QtWidgets.QGroupBox(self.centralwidget)
        self.KiBox.setGeometry(QtCore.QRect(10, 260, 189, 74))
        self.KiBox.setObjectName("KiBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.KiBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.KiSpinBox = QtWidgets.QDoubleSpinBox(self.KiBox)
        self.KiSpinBox.setObjectName("KiSpinBox")
        self.gridLayout_3.addWidget(self.KiSpinBox, 0, 0, 1, 1)
        self.KiSendButton = QtWidgets.QPushButton(self.KiBox)
        self.KiSendButton.setObjectName("KiSendButton")
        self.gridLayout_3.addWidget(self.KiSendButton, 0, 1, 1, 1)
        self.KdBox = QtWidgets.QGroupBox(self.centralwidget)
        self.KdBox.setGeometry(QtCore.QRect(10, 360, 189, 74))
        self.KdBox.setObjectName("KdBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.KdBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.KdSpinBox = QtWidgets.QDoubleSpinBox(self.KdBox)
        self.KdSpinBox.setObjectName("KdSpinBox")
        self.gridLayout_4.addWidget(self.KdSpinBox, 0, 0, 1, 1)
        self.KdSendButton = QtWidgets.QPushButton(self.KdBox)
        self.KdSendButton.setObjectName("KdSendButton")
        self.gridLayout_4.addWidget(self.KdSendButton, 0, 1, 1, 1)
        self.PIDParametersBox = QtWidgets.QGroupBox(self.centralwidget)
        self.PIDParametersBox.setGeometry(QtCore.QRect(10, 460, 191, 121))
        self.PIDParametersBox.setObjectName("PIDParametersBox")
        self.KdLabel = QtWidgets.QLabel(self.PIDParametersBox)
        self.KdLabel.setGeometry(QtCore.QRect(10, 90, 171, 21))
        self.KdLabel.setObjectName("KdLabel")
        self.KiLabel = QtWidgets.QLabel(self.PIDParametersBox)
        self.KiLabel.setGeometry(QtCore.QRect(10, 60, 171, 21))
        self.KiLabel.setObjectName("KiLabel")
        self.KpLabel = QtWidgets.QLabel(self.PIDParametersBox)
        self.KpLabel.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.KpLabel.setObjectName("KpLabel")
        self.RefreshPortButton = QtWidgets.QPushButton(self.centralwidget)
        self.RefreshPortButton.setGeometry(QtCore.QRect(450, 10, 41, 31))
        icon = QtGui.QIcon.fromTheme("refresh")
        self.RefreshPortButton.setIcon(icon)
        self.RefreshPortButton.setObjectName("RefreshPortButton")
        self.GraphicViewUpLeftLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphicViewUpLeftLabel.setGeometry(QtCore.QRect(240, 310, 79, 19))
        self.GraphicViewUpLeftLabel.setObjectName("GraphicViewUpLeftLabel")
        self.GraphicViewBottomLeftLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphicViewBottomLeftLabel.setGeometry(QtCore.QRect(240, 560, 79, 19))
        self.GraphicViewBottomLeftLabel.setObjectName("GraphicViewBottomLeftLabel")
        self.GraphicViewBottomCenterLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphicViewBottomCenterLabel.setGeometry(QtCore.QRect(540, 560, 79, 19))
        self.GraphicViewBottomCenterLabel.setObjectName("GraphicViewBottomCenterLabel")
        self.GraphicViewUpRightLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphicViewUpRightLabel.setGeometry(QtCore.QRect(700, 310, 79, 19))
        self.GraphicViewUpRightLabel.setObjectName("GraphicViewUpRightLabel")
        self.GraphicViewBottomRightLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphicViewBottomRightLabel.setGeometry(QtCore.QRect(850, 560, 79, 19))
        self.GraphicViewBottomRightLabel.setObjectName("GraphicViewBottomRightLabel")
        self.PlotWidgetUpLeft = PlotWidget(self.centralwidget)
        self.PlotWidgetUpLeft.setGeometry(QtCore.QRect(229, 49, 451, 281))
        self.PlotWidgetUpLeft.setObjectName("PlotWidgetUpLeft")
        self.PlotWidgetUpRight = PlotWidget(self.centralwidget)
        self.PlotWidgetUpRight.setGeometry(QtCore.QRect(690, 50, 451, 281))
        self.PlotWidgetUpRight.setObjectName("PlotWidgetUpRight")
        self.PlotWidgetBottomLeft = PlotWidget(self.centralwidget)
        self.PlotWidgetBottomLeft.setGeometry(QtCore.QRect(230, 340, 291, 241))
        self.PlotWidgetBottomLeft.setObjectName("PlotWidgetBottomLeft")
        self.PlotWidgetBottomCenter = PlotWidget(self.centralwidget)
        self.PlotWidgetBottomCenter.setGeometry(QtCore.QRect(530, 340, 301, 241))
        self.PlotWidgetBottomCenter.setObjectName("PlotWidgetBottomCenter")
        self.PlotWidgetBottomRight = PlotWidget(self.centralwidget)
        self.PlotWidgetBottomRight.setGeometry(QtCore.QRect(840, 340, 301, 241))
        self.PlotWidgetBottomRight.setObjectName("PlotWidgetBottomRight")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PID Tuner"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.SetPointBox.setTitle(_translate("MainWindow", "Setpoint Control"))
        self.SetPointSendButton.setText(_translate("MainWindow", "Send"))
        self.KpBox.setTitle(_translate("MainWindow", "Kp Control"))
        self.KpSendButton.setText(_translate("MainWindow", "Send"))
        self.KiBox.setTitle(_translate("MainWindow", "Ki Control"))
        self.KiSendButton.setText(_translate("MainWindow", "Send"))
        self.KdBox.setTitle(_translate("MainWindow", "Kd Control"))
        self.KdSendButton.setText(_translate("MainWindow", "Send"))
        self.PIDParametersBox.setTitle(_translate("MainWindow", "PID Parameters"))
        self.KdLabel.setText(_translate("MainWindow", "Kd: 10"))
        self.KiLabel.setText(_translate("MainWindow", "Ki: 10"))
        self.KpLabel.setText(_translate("MainWindow", "Kp: 10"))
        self.RefreshPortButton.setText(_translate("MainWindow", "R"))
        self.GraphicViewUpLeftLabel.setText(_translate("MainWindow", "TextLabel"))
        self.GraphicViewBottomLeftLabel.setText(_translate("MainWindow", "TextLabel"))
        self.GraphicViewBottomCenterLabel.setText(_translate("MainWindow", "TextLabel"))
        self.GraphicViewUpRightLabel.setText(_translate("MainWindow", "TextLabel"))
        self.GraphicViewBottomRightLabel.setText(_translate("MainWindow", "TextLabel"))


from pyqtgraph import PlotWidget
